{
 "title": "Dameng Database",
 "tags": [ "Dameng Database" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dbname",
    "label": "DB Name",
    "query": {
     "query": "label_values(target_info{ojr=\"dameng-db\"},db_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DB Address",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max( target_info{ojr=\"dameng-db\", db_name=\"$dbname\"} ) by (db_address)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Port",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max( target_info{ojr=\"dameng-db\", db_name=\"$dbname\"} ) by (db_port)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max( target_info{ojr=\"dameng-db\", db_name=\"$dbname\"} ) by (db_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_instance_active_count{db_name=\"$dbname\"}",
     "legendFormat": "All"
    },
    {
     "expr": "db_instance_count{db_name=\"$dbname\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "db_session_count{db_name=\"$dbname\"}",
     "legendFormat": "Total Sessions"
    },
    {
     "expr": "db_session_active_count{db_name=\"$dbname\"}",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "SQL rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "db_sql_rate{db_name=\"$dbname\"}",
     "legendFormat": "SQL rate"
    }
   ]
  },
  {
   "title": "Transaction latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_transaction_latency_seconds{db_name=\"$dbname\"}",
     "legendFormat": "Transaction latency"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "db_transaction_rate{db_name=\"$dbname\"}",
     "legendFormat": "Transaction rate"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "db_cache_hit_ratio{db_name=\"$dbname\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Task wait count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "db_task_wait_count{db_name=\"$dbname\"}",
     "legendFormat": "Wait count"
    }
   ]
  },
  {
   "title": "Task wait time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_task_avg_wait_time_seconds{db_name=\"$dbname\"}",
     "legendFormat": "Wait time"
    }
   ]
  },
  {
   "title": "Tablespace usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "db_tablespace_utilization_ratio{db_name=\"$dbname\"}",
     "legendFormat": "{{tablespace_name}}"
    }
   ]
  },
  {
   "title": "CPU usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "db_cpu_utilization_ratio{db_name=\"$dbname\"}",
     "legendFormat": "usage ratio"
    }
   ]
  },
  {
   "title": "Memory usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "db_mem_utilization_ratio {db_name=\"$dbname\"}",
     "legendFormat": "usage ratio"
    }
   ]
  },
  {
   "title": "Disk usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "db_disk_utilization_ratio{db_name=\"$dbname\"}",
     "legendFormat": "usage ratio"
    }
   ]
  },
  {
   "title": "Most time-consuming SQL statements",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT Value, TimeUnix as \"time\", Attributes FROM test.otel_metrics_sum WHERE ( time >= $__fromTime AND time <= $__toTime ) and MetricName = 'db.sql.elapsed_time' ORDER BY Value DESC LIMIT 10"
    }
   ]
  }
 ]
}