{
 "title": "IBM MQ",
 "description": "Monitoring for IBM MQ Queue Managers",
 "tags": [ "IBM MQ" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "qmgr",
    "label": "Queue Manager",
    "query": {
     "query": "label_values(ibmmq_qmgr_metadata,queueManager)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Queue Manager Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_status{queueManager=\"$qmgr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_cmd_level{queueManager=\"$qmgr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Manager Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "max(ibmmq_qmgr_metadata{queueManager=\"$qmgr\"}) by(host_name,platform,queueManager,version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_start_time_seconds{queueManager=\"$qmgr\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_connection_count{queueManager=\"$qmgr\"}",
     "legendFormat": "{{queueManager}}@{{host_name}}"
    },
    {}
   ]
  },
  { "title": "Queue Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Queue Configuration",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(ibmmq_queue_metadata{queueManager=\"$qmgr\"}) by (queue, delivery, type, usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Depth Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg(ibmmq_queue_depth{queueManager=\"$qmgr\"}) by(queue) / avg(ibmmq_queue_max_depth{queueManager=\"$qmgr\"}) by(queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Input",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(ibmmq_queue_open_input{queueManager=\"$qmgr\"}) by(queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Output",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(ibmmq_queue_open_output{queueManager=\"$qmgr\"}) by(queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Listener Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Listener Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max( ibmmq_listener_status{queueManager=\"$qmgr\"} ) by (listener)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener Configuration",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "max( ibmmq_listener_metadata{queueManager=\"$qmgr\"} ) by (listener, ip, port)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Channel Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Channel Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(ibmmq_channel_status{queueManager=\"$qmgr\"} ) by(channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "max( ibmmq_channel_type{queueManager=\"$qmgr\"} ) by (channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Doubt Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "max( ibmmq_channel_indoubt_status{queueManager=\"$qmgr\"} ) by (channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Buffers Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "avg( rate(ibmmq_channel_buffers_sent_total{queueManager=\"$qmgr\"}[2m]) * 120 ) by(channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Buffers Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "avg( rate(ibmmq_channel_buffers_received_total{queueManager=\"$qmgr\"}[2m]) * 120) by(channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg( rate(ibmmq_channel_bytes_sent_total{queueManager=\"$qmgr\"}[2m]) * 120 ) by(channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "avg( rate(ibmmq_channel_bytes_received_total{queueManager=\"$qmgr\"}[2m]) * 120) by(channel)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}